name: MyNebo-CI-CD-Pipeline
env:
  AWS_REGION_NAME: "eu-central-1"
  DOCKER IMAGE_NAME: "FlaskAPP-"

on:
  push:
    # Match all branches *without* a / in the name.
    # This will exclude "sub" branches, such as "feature branches",
    # named something like: "feature/my-feature". Those branches will
    # likely contain "work in progress" code, so we will run the tests
    # on the local machine and avoid using up GitHub Actions credits
    # (if applicable, such as in `private` repositories).
    # Filter syntax info: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
    branches:
      - 'stage'
      - 'master'
  pull_request:
    # Since pull requests come from "third parties", we will automatically
    # test everything coming from the outside world, for good measure.
    # The `branches` tag could also be omitted, yielding the same effect here.
    branches:
      - 'stage'
      - 'master'



jobs:
  # Run code tests before building the image, to ensure it is good to go
  testing_step:
    name: Run code tests
    runs-on: ubuntu-latest


    steps:

    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Setting up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Initalize and seed the database
      run: |
        flask db upgrade
        python seed.py
    - name: Lint the code with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # - name: Test with unittest
    #   run: |
    #     python -m unittest discover
    #     echo "Testing finished successfully"
  # Build and push the Docker image

  building_step:
    name: Building image
    runs-on: ubuntu-latest
    needs: testing_step


    steps:
    - name: Configure AWS connections
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.MY_PRIVATE_AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.MY_PRIVATE_AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{env.AWS_REGION_NAME}}
    - uses: actions/checkout@v2

    - name: Connection to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.MY_PRIVATE_AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.MY_PRIVATE_AWS_SECRET_ACCESS_KEY}}

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
#Build image
    # - name: Build image and push to ECR registry with latest tag
    #   env:
    #     AWS_REGION: ${{env.AWS_REGION_NAME}}
    #     ECR_REPOSITORY: "nebo-repo"
    #     ECR_REGISTRY: ${{env.AWS_ECR_REGISTRY}}
    #     IMAGE_TAG: latest
    #   run: |
    #     export ECR_REGISTRY=${{steps.login-ecr.outputs.registry}}
    #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    #     echo "Pushing image to ECR..."
    #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    #     echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    # - name: Build image and push to ECR registry with sha_short
    #   env:
    #     AWS_REGION: ${{env.AWS_REGION_NAME}}
    #     ECR_REPOSITORY: "nebo-repo"
    #     ECR_REGISTRY: ${{env.AWS_ECR_REGISTRY}}


    #   run: |
    #       export ECR_REGISTRY=${{steps.login-ecr.outputs.registry}}
    #       docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.vars.outputs.sha_short }} .
    #       echo "Pushing image to ECR..."
    #       echo " sha_short is ${{ steps.vars.outputs.sha_short }}"
    #       docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.vars.outputs.sha_short }}
    #       echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.vars.outputs.sha_short }}"

  deploing_stage:
    name: Deploying to stage
    runs-on: ubuntu-latest
    needs: building_step
    if: github.ref == 'refs/heads/stage'

    steps:
    - name: Print value from previus job
      run: echo " STAGE- sha_short is ${{ steps.vars.outputs.sha_short }}"

    - uses: actions/checkout@v2

    - name: Configure AWS connections
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.MY_PRIVATE_AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.MY_PRIVATE_AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{env.AWS_REGION_NAME}}

    - name: Connection to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.MY_PRIVATE_AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.MY_PRIVATE_AWS_SECRET_ACCESS_KEY}}

    - name: Deployng into ASG-STAGE
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.MY_PRIVATE_AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.MY_PRIVATE_AWS_SECRET_ACCESS_KEY}}
        ASG_STAGE: ${{secrets.ASG_STAGE}}
        AWS_REGION: ${{env.AWS_REGION_NAME}}
        ECR_REGISTRY: ${{env.ECR_REGISTRY}}
        ECR_REPOSITORY: ${{env.ECR_REPOSITORY}}

      run: |
        echo "Start deploying to ASG-STAGE"
        DOCKER_IMAGE=${{steps.login-ecr.outputs.registry}}/${{secrets.ECR_REPOSITORY}}:latest
        chmod +x deploy.sh
        ./deploy.sh $ASG_STAGE $DOCKER_IMAGE $AWS_REGION
        ls

#####################  DEPLOY TO PROD###################################



  deploing_prod: #Com
    name: Deploying to prod
    runs-on: ubuntu-latest
    needs: building_step
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
    - name: Print value from previus job prod
      run: |
        echo " PROD sha_short is ${{ steps.vars.outputs.sha_short }}"
        echo $image

#####################   NOTIFICATION    ###################################
  notification_stage:
    name: Slack notification
    runs-on: ubuntu-latest
    needs: deploing_stage
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Deploy to STAGE was successful !!! :rocket:'














